name: Build and Push to ECR

on:
  push:
    branches: [main]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  push-to-ecr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Build and Push Frontend
      - name: Build and Push Frontend
        run: |
          docker build -t ${{ secrets.ECR_REPO_FRONTEND }}:latest ./frontend
          docker push ${{ secrets.ECR_REPO_FRONTEND }}:latest

      # Build and Push Backend
      - name: Build and Push Backend
        run: |
          docker build -t ${{ secrets.ECR_REPO_BACKEND }}:latest ./backend
          docker push ${{ secrets.ECR_REPO_BACKEND }}:latest
